ALTER TABLE users DROP COLUMN IF EXISTS password_hash;
ALTER TABLE users ALTER COLUMN oauth_provider SET NOT NULL;
ALTER TABLE users ALTER COLUMN oauth_id SET NOT NULL;
ALTER TABLE users DROP COLUMN IF EXISTS username;
